version: 2
updates:
  - package-ecosystem: cargo
    directory: "code/apps/cli"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: "crates/disaronno"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: "crates/macros"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10